### ISSUE TITLE
Error during NPM install with Node v0.11.9

### ISSUE THREAD

**Issue by dankirkpatrick** [jprichardson/node-kexec#10]
I'm trying to instal kexec on an ARM linux box with the latest unstable Node release, 0.11.9.  I'm getting the following error, which seems to indicate that I'm not getting fcntl.h from /usr/include/arm-linux-gnueabi/bits/fcntl.h (or maybe /usr/include/asm-generic/fcntl.h?).  

Do I have an incorrect include path?  Any suggestions for fixing it?  Is this problem isolated to the unstable Node release?  I am unable to build the latest stable Node release due to an unrelated issue, so I am unable to verify if the problem also exists with v0.10.x.

Here's the error I get when running "npm install kexec":

> kexec@0.2.0 install /home/ubuntu/node_modules/kexec
> node-gyp configure build

make: Entering directory `/home/ubuntu/node_modules/kexec/build'
  CXX(target) Release/obj.target/kexec/src/kexec.o
../src/kexec.cc: In function 'int clear_cloexec(int)':
../src/kexec.cc:21:30: error: 'F_GETFD' was not declared in this scope
../src/kexec.cc:21:40: error: 'fcntl' was not declared in this scope
../src/kexec.cc:25:15: error: 'FD_CLOEXEC' was not declared in this scope
../src/kexec.cc:26:25: error: 'F_SETFD' was not declared in this scope
../src/kexec.cc: At global scope:
../src/kexec.cc:37:34: error: 'Arguments' does not name a type
../src/kexec.cc:37:45: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
/home/ubuntu/.node-gyp/0.11.9/deps/v8/include/v8.h: In function 'v8::Handle<v8::Value> kexec(const int&)':
/home/ubuntu/.node-gyp/0.11.9/deps/v8/include/v8.h:768:13: error: 'v8::HandleScope::HandleScope()' is private
../src/kexec.cc:38:14: error: within this context
../src/kexec.cc:58:20: error: request for member 'Length' in 'args', which is of non-class type 'const int'
../src/kexec.cc:58:38: error: invalid types 'const int[int]' for array subscript
../src/kexec.cc:60:39: error: invalid types 'const int[int]' for array subscript
../src/kexec.cc:68:20: error: request for member 'Length' in 'args', which is of non-class type 'const int'
../src/kexec.cc:68:38: error: invalid types 'const int[int]' for array subscript
../src/kexec.cc:68:61: error: invalid types 'const int[int]' for array subscript
../src/kexec.cc:70:39: error: invalid types 'const int[int]' for array subscript
../src/kexec.cc:74:61: error: invalid types 'const int[int]' for array subscript
../src/kexec.cc: In function 'void init(v8::Handle<v8::Object>)':
../src/kexec.cc:105:47: error: no matching function for call to 'NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [6], v8::Handle<v8::Value> (&)(const int&))'
../src/kexec.cc:105:47: note: candidate is:
/home/ubuntu/.node-gyp/0.11.9/src/node.h:152:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
make: *** [Release/obj.target/kexec/src/kexec.o] Error 1
make: Leaving directory `/home/ubuntu/node_modules/kexec/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Linux 3.0.35
gyp ERR! command "node" "/opt/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/ubuntu/node_modules/kexec
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
npm ERR! kexec@0.2.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kexec@0.2.0 install script.
npm ERR! This is most likely a problem with the kexec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls kexec
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.0.35
npm ERR! command "/opt/bin/node" "/opt/bin/npm" "install" "kexec"
npm ERR! cwd /home/ubuntu
npm ERR! node -v v0.11.9
npm ERR! npm -v 1.3.15
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/npm-debug.log
npm ERR! not ok code 0

**Comment by jprichardson** [comment]
Try the latest version and let me know if it solves your problem.
