### ISSUE TITLE
configure failed

### ISSUE THREAD

**Issue by usarthurchoi** [jprichardson/node-kexec#14]
Tried to build io.js first time.
Got the following error from ./configure.
Any ideas? It seems I have all the prereqs.

~/git/io.js$ ./configure
creating  ./icu_config.gypi
{'variables': {'node_shared_http_parser': 'false',
'want_separate_host_toolset': 0, 'icu_small': 'false', 'node_use_mdb':
'false', 'target_arch': 'x64', 'host_arch': 'x64', 'v8_optimized_debug': 0,
'node_install_npm': 'true', 'openssl_no_asm': 0, 'uv_parent_path':
'/deps/uv/', 'v8_no_strict_aliasing': 1, 'node_shared_zlib': 'false',
'node_use_dtrace': 'true', 'python': '/Library/Frameworks/Python.framework/Ver
sions/2.7/Resources/Python.app/Contents/MacOS/Python', 'v8_enable_gdbjit': 0,
'node_use_etw': 'false', 'v8_enable_i18n_support': 0, 'node_use_perfctr':
'false', 'v8_random_seed': 0, 'node_prefix': '', 'node_shared_openssl':
'false', 'uv_use_dtrace': 'true', 'node_shared_v8': 'false',
'node_use_openssl': 'true', 'uv_library': 'static_library', 'v8_use_snapshot':
'true', 'node_shared_libuv': 'false', 'node_tag': ''}, 'target_defaults':
{'libraries': [], 'default_configuration': 'Release', 'cflags': [],
'include_dirs': [], 'defines': []}}
creating  ./config.gypi
creating  ./config.mk
2015-01-22 14:12:50.319 xcodebuild[3373:72277] error: (null)
~/git/io.js$

===

~/git/io.js$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

~/git/io.js$ uname -a
Darwin .. 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

**Comment by jprichardson** [comment]
And you've ran `npm install -g pangyp` ?
